### ISSUE TITLE
Feature request : ability to send error responses 

### ISSUE THREAD

**Issue by samyilias** [Fcmam5/express-response-presnter#1]
As a backend dev I want to use `express-response-presenter` to send error status for things such as `400`,`401`,`404`,`5xx`

**Comment by Fcmam5** [comment]
For errors, there's [@hapi/boom](https://github.com/hapijs/boom) and it takes care of handling such errors in a very elegant way. I wasn't sure if I will be reinventing the wheel or maybe adding some useless functions.

What do you think? Does it make sense to copy rework on it in this library as well? Or should we use @hapi/boom as a dependency and forward all "unhappy responses" to it?

**Comment by samyilias** [comment]
@Fcmam5 my bad , I thought it was meant to be an alternative to [express-boom]() . you are right no need to reinvent the wheel 
however , the name of the library should highlight that it only deals with happy responses . 
how about `express-happy-presenter `
